import type { Constellation } from "./astronomy";

export const CONSTELLATIONS: Constellation[] = [
{
    id: "orion",
    name: "Orion",
    nameJa: "オリオン座",
    stars: ["Betelgeuse", "Rigel", "Bellatrix", "Saiph", "Alnilam", "Alnitak", "Mintaka"],
    lines: [
    ["Betelgeuse", "Bellatrix"],
    ["Betelgeuse", "Alnilam"],
    ["Bellatrix", "Mintaka"],
    ["Rigel", "Alnilam"],
    ["Saiph", "Alnitak"],
    ["Alnilam", "Alnitak"],
    ["Alnitak", "Mintaka"],
    ["Rigel", "Mintaka"],
    ["Saiph", "Alnilam"],
    ],
    description: "冬の夜空でいちばん見つけやすい星座だよ！三つ並んだ星（三ツ星）が目印。",
    myth:"ギリシャ神話の狩人オリオンの姿。とっても強くて勇敢な狩人だったんだって！さそり座のサソリに刺されてしまい、空に上げられて星座になったと言われているよ。",
    emoji: "⚔️",
    season: "winter",
    trivia: ["三ツ星はベルトの位置。写真でも見つけやすいよ。", "明るい星が多くて街明かりがあっても見つけやすい。"],
    genres: ["hero", "myth", "winterDiamond"],
},
{
    id: "ursa-major",
    name: "Ursa Major",
    nameJa: "おおぐま座（北斗七星）",
    stars: ["Dubhe", "Merak", "Phecda", "Megrez", "Alioth", "Mizar", "Alkaid"],
    lines: [
    ["Dubhe", "Merak"],
    ["Merak", "Phecda"],
    ["Phecda", "Megrez"],
    ["Megrez", "Alioth"],
    ["Alioth", "Mizar"],
    ["Mizar", "Alkaid"],
    ["Dubhe", "Megrez"],
    ],
    description: "北の空にある大きなひしゃく（おたま）の形！北斗七星とも呼ばれるよ。",
    myth: "ゼウスという神様が、美しいカリストを大きなクマに変えて空に上げたんだ。いつも北の空でクルクル回っているよ。",
    emoji: "🐻",
    season: "spring",
    trivia: ["ひしゃくの外側2つ（ドゥーベ→メラク）を伸ばすと北極星の方向がわかるよ。", "季節で向きが回転して見えるよ。"],
    genres: ["animal", "myth", "northern"],
},
{
    id: "scorpius",
    name: "Scorpius",
    nameJa: "さそり座",
    stars: ["Antares", "Shaula", "Sargas"],
    lines: [
    ["Antares", "Shaula"],
    ["Shaula", "Sargas"],
    ],
    description: "夏の夜空に見える赤い星アンタレスが目印！S字の形をしているよ。",
    myth: "オリオンを刺したサソリが星座になったんだ。だからオリオン座とさそり座は同時に見えないって知ってた？",
    emoji: "🦂",
    season: "summer",
    trivia: ["アンタレスは赤くて目立つよ。", "南の空に低めに見えることが多いよ（日本では特に）。"],
    genres: ["animal", "myth", "zodiac"],
},
{
    id: "lyra",
    name: "Lyra",
    nameJa: "こと座",
    stars: ["Vega", "Sulafat", "Sheliak"],
    lines: [
    ["Vega", "Sheliak"],
    ["Vega", "Sulafat"],
    ["Sheliak", "Sulafat"],
    ],
    description: "夏の大三角のひとつ、ベガ（織姫星）がある星座！とっても明るいよ。",
    myth:"七夕の織姫星として有名！天の川をはさんで、彦星（アルタイル）と向かい合っているよ。年に一度、七夕の日に会えるんだって。",
    emoji: "🎵",
    season: "summer",
    trivia: ["こと座は星座としては小さいけど、ベガがとても明るいよ。", "夏の大三角の“目印”として超有能。"],
    genres: ["myth", "summerTriangle", "tool"],
},
{
    id: "cygnus",
    name: "Cygnus",
    nameJa: "はくちょう座",
    stars: ["Deneb", "Sadr", "Gienah Cygni", "Albireo", "Fawaris"],
    lines: [
    ["Deneb", "Sadr"],
    ["Sadr", "Albireo"],
    ["Gienah Cygni", "Sadr"],
    ["Sadr", "Fawaris"],
    ],
    description: "夏の大三角のひとつ、デネブがある星座。天の川の中を飛ぶ白鳥の形！",
    myth: "ゼウスが白鳥に変身した姿だと言われているよ。天の川の中を優雅に飛んでいるように見えるね。",
    emoji: "🦢",
    season: "summer",
    trivia: ["天の川が濃い場所にあって双眼鏡で見ると楽しいよ。", "デネブは“遠くて明るい”タイプの星として有名。"],
    genres: ["animal", "myth", "summerTriangle"],
},
{
    id: "gemini",
    name: "Gemini",
    nameJa: "ふたご座",
    stars: ["Pollux", "Castor"],
    lines: [["Pollux", "Castor"]],
    description: "冬から春に見える星座。ポルックスとカストルの二つの明るい星が目印！",
    myth: "仲良しの双子の兄弟、カストルとポルックスの物語。二人はいつも一緒で、星座になっても隣り合っているよ。",
    emoji: "👬",
    season: "winter",
    trivia: ["ポルックスとカストルは“頭”の位置。そこから体が伸びるイメージ。", "形がシンプルで見つけやすいよ。"],
    genres: ["hero", "myth", "zodiac"],
},
{
    id: "leo",
    name: "Leo",
    nameJa: "しし座",
    stars: ["Regulus", "Denebola"],
    lines: [["Regulus", "Denebola"]],
    description: "春の夜空に見える星座。レグルスという明るい星が心臓の位置にあるよ！",
    myth: "ヘラクレスが退治した最強のライオン。とっても強くて、ヘラクレスでさえ苦労したんだって！",
    emoji: "🦁",
    season: "spring",
    trivia: ["レグルスは“王”っぽい名前で知られているよ。", "黄道十二星座の1つ。"],
    genres: ["animal", "myth", "zodiac"],
},
{
    id: "cassiopeia",
    name: "Cassiopeia",
    nameJa: "カシオペヤ座",
    stars: ["Schedar", "Caph", "Navi", "Ruchbah", "Segin"],
    lines: [
    ["Caph", "Schedar"],
    ["Schedar", "Navi"],
    ["Navi", "Ruchbah"],
    ["Ruchbah", "Segin"],
    ],
    description: "Wの形をした星座！北極星を見つけるときの目印になるよ。",
    myth:"自分の美しさを自慢しすぎた女王カシオペヤ。罰として椅子にしばられたまま空をクルクル回ることになったんだ。",
    emoji: "👑",
    season: "all",
    trivia: ["北の空の“W”が目印。北極星探しの相棒！", "北斗七星が低い季節でも頼れることがあるよ。"],
    genres: ["hero", "myth", "northern"],
},
{
    id: "ursa-minor",
    name: "Ursa Minor",
    nameJa: "こぐま座",
    stars: ["Polaris", "Kochab", "Pherkad", "Yildun", "Zeta UMi", "Eta UMi"],
    lines: [
      ["Polaris", "Yildun"],
      ["Yildun", "Zeta UMi"],
      ["Zeta UMi", "Eta UMi"],
      ["Eta UMi", "Pherkad"],
      ["Pherkad", "Kochab"],
      ["Kochab", "Zeta UMi"],
    ],
    description: "北極星（ポラリス）がある星座だよ。北の方向の目印になる！",
    myth: "ギリシャ神話では「小さなクマ」とされる星座。北の空でいつも見つけやすいんだ。",
    emoji: "🐻‍❄️",
    season: "all",
    trivia: ["北極星はほぼ動かないので、方角の基準になるよ。", "星座は小さいけど、重要度は特大。"],
    genres: ["animal", "myth", "northern"],
  },
  {
    id: "virgo",
    name: "Virgo",
    nameJa: "おとめ座",
    stars: ["Spica"],
    lines: [],
    description: "春の夜空に見える星座。いちばん明るい星スピカが目印！",
    myth: "豊穣や正義を象徴する「乙女」の姿だと言われるよ。スピカは麦の穂（収穫）を表すこともあるんだ。",
    emoji: "🌾",
    season: "spring",
    trivia: ["「アークトゥルス→スピカ」とたどる見つけ方が有名だよ。", "黄道十二星座の1つ。"],
    genres: ["hero", "myth", "zodiac"],
  },
  {
    id: "bootes",
    name: "Bootes",
    nameJa: "うしかい座",
    stars: ["Arcturus", "Izar", "Muphrid", "Nekkar", "Seginus"],
    lines: [
      ["Arcturus", "Muphrid"],
      ["Arcturus", "Izar"],
      ["Izar", "Seginus"],
      ["Seginus", "Nekkar"],
      ["Nekkar", "Izar"],
    ],
    description: "春〜初夏に目立つ星座。オレンジ色っぽく明るいアークトゥルスが超目印！",
    myth: "牛を追いかける「牛飼い」の姿の星座。北斗七星のカーブをのばすとアークトゥルスにたどり着くよ。",
    emoji: "🐄",
    season: "spring",
    trivia: ["北斗七星の柄のカーブを伸ばすとアークトゥルスに当たる（春の定番テク）。", "アークトゥルスはオレンジ色が分かりやすいよ。"],
    genres: ["hero", "myth"],
  },
  {
    id: "hydra",
    name: "Hydra",
    nameJa: "うみへび座",
    stars: ["Alphard"],
    lines: [],
    description: "とっても長い星座！いちばん明るい星はアルファルド。",
    myth: "ギリシャ神話の「怪物ヒュドラ」に由来するよ。星座自体が長〜く空にのびているんだ。",
    emoji: "🐍",
    season: "spring",
    trivia: ["全天でも特に長い星座のひとつ。全部追うのは難しいよ。", "アルファルドは周りに明るい星が少なくて目立つ。"],
    genres: ["animal", "myth", "sea"],
  },
  {
    id: "canis-minor",
    name: "Canis Minor",
    nameJa: "こいぬ座",
    stars: ["Procyon"],
    lines: [],
    description: "冬の空で見つけやすい小さな星座。プロキオンがピカッと光るよ！",
    myth: "オリオンのそばを走る「小さな犬」とされる星座だよ。",
    emoji: "🐶",
    season: "winter",
    trivia: ["星座は小さいけどプロキオンが明るいので見つけやすい。", "冬の明るい星並び（冬の大六角形など）の話題に出やすいよ。"],
    genres: ["animal", "myth", "winterDiamond"],
  },
  {
    id: "canis-major",
    name: "Canis Major",
    nameJa: "おおいぬ座",
    stars: ["Sirius", "Adhara", "Wezen", "Murzim"],
    lines: [
      ["Sirius", "Murzim"],
      ["Sirius", "Wezen"],
      ["Wezen", "Adhara"],
      ["Adhara", "Sirius"],
    ],
    description: "全天でいちばん明るい星、シリウスがいる星座！冬の主役級。",
    myth: "オリオンと一緒に空を走る「大きな犬」の星座だと言われているよ。",
    emoji: "🐕",
    season: "winter",
    trivia: ["シリウスは全天で最も明るい恒星として有名。", "低い位置だと色がチカチカ変わって見えることがあるよ（大気のゆらぎ）。"],
    genres: ["animal", "myth", "winterDiamond"],
  },
  {
    id: "taurus",
    name: "Taurus",
    nameJa: "おうし座",
    stars: ["Aldebaran", "Elnath", "Hyadum I", "Ain"],
    lines: [
      ["Hyadum I", "Aldebaran"],
      ["Ain", "Aldebaran"],
      ["Aldebaran", "Elnath"],
    ],
    description: "冬の星座。赤っぽい明るい星アルデバランが「目」の位置にあるよ！",
    myth: "ギリシャ神話の「雄牛」の姿。アルデバランは燃えるような赤さで目立つんだ。",
    emoji: "🐂",
    season: "winter",
    trivia: ["アルデバランは赤っぽくて目立つよ。", "黄道十二星座の1つ。月が近くを通ることも多い。"],
    genres: ["animal", "myth", "winterDiamond", "zodiac"],
  },
  {
    id: "auriga",
    name: "Auriga",
    nameJa: "ぎょしゃ座",
    stars: ["Capella", "Menkalinan", "Mahasim", "Hassaleh", "Elnath"],
    lines: [
      ["Capella", "Menkalinan"],
      ["Menkalinan", "Mahasim"],
      ["Mahasim", "Elnath"],
      ["Elnath", "Hassaleh"],
      ["Hassaleh", "Capella"],
    ],
    description: "冬の空で明るいカペラが目印！黄色っぽく見えることもあるよ。",
    myth: "戦車（馬車）をあやつる「御者」の姿の星座だと言われているよ。",
    emoji: "🛷",
    season: "winter",
    trivia: ["カペラは冬の空でかなり目立つ明るい星の1つ。", "星座自体は大きめ。周辺の星も拾うと形が見えてくるよ。"],
    genres: ["hero", "myth", "winterDiamond"],
  },
  {
    id: "aquila",
    name: "Aquila",
    nameJa: "わし座",
    stars: ["Altair", "Tarazed", "Alshain"],
    lines: [
      ["Tarazed", "Altair"],
      ["Altair", "Alshain"],
    ],
    description:
      "夏の夜空で見つけやすい星座。明るい星アルタイル（彦星）が目印で、天の川の近くに見えるよ。",
    myth:
      "ギリシャ神話では、大神ゼウスの使いのワシ。雷（いかずち）を運ぶ役目だった、と言われることもあるよ。",
    emoji: "🦅",
    season: "summer",
    trivia: [
      "アルタイルは夏の大三角の1つ（ベガ・デネブ・アルタイル）。",
      "七夕の「彦星（ひこぼし）」として有名。天の川をはさんでベガ（織姫星）と向かい合うよ。",
    ],
    genres: ["animal", "myth", "summerTriangle"],
  },
  {
    id: "piscis-austrinus",
    name: "Piscis Austrinus",
    nameJa: "みなみのうお座",
    stars: ["Fomalhaut"],
    lines: [],
    description:
      "秋の夜空の南の低いところに見えやすい星座。明るい星フォーマルハウトが“ぽつん”と光って見つけやすいよ。",
    myth:
      "名前は「南の魚」という意味。古い時代から“魚の姿”として考えられてきた星座のひとつだよ。",
    emoji: "🐟",
    season: "autumn",
    trivia: [
      "フォーマルハウトは周りに明るい星が少ないので、暗い空だと目立ちやすい。",
      "日本だと南の空の低い位置に出ることが多いので、建物や山に隠れやすいよ。",
    ],
    genres: ["animal", "myth", "sea"],
  },
  {
    id: "carina",
    name: "Carina",
    nameJa: "りゅうこつ座",
    stars: ["Canopus"],
    lines: [],
    description:
      "南の空にある星座で、カノープスがいちばん有名。日本では地域によっては地平線近くにやっと見える“レア星”だよ。",
    myth:
      "昔は「アルゴ船」という大きな船の星座の一部と考えられていて、りゅうこつ座はその“船底（竜骨）”の部分なんだ。",
    emoji: "🛶",
    season: "winter",
    trivia: [
      "カノープスは全天でとても明るい星（シリウスの次クラス）だけど、日本だと低くて見えにくいことがある。",
      "南の視界がひらけた場所（海辺や高い場所）だと見つけやすいよ。",
    ],
    genres: ["myth", "sea", "tool"],
  },
  {
    id: "sagittarius",
    name: "Sagittarius",
    nameJa: "いて座",
    stars: ["Kaus Australis", "Nunki", "Ascella", "Kaus Media", "Kaus Borealis", "Alnasl"],
    lines: [
      ["Kaus Media", "Kaus Borealis"],
      ["Kaus Borealis", "Nunki"],
      ["Nunki", "Ascella"],
      ["Ascella", "Kaus Australis"],
      ["Kaus Australis", "Kaus Media"],
      ["Kaus Borealis", "Alnasl"],
      ["Alnasl", "Kaus Australis"],
    ],
    description: "夏の天の川が一番濃いあたりに見える「ティーポット」の形が目印だよ。",
    myth: "弓を引くケンタウロス（半人半馬の賢者）の姿。矢の先は、さそり座の心臓アンタレスを狙っているんだ。",
    emoji: "🏹",
    season: "summer",
    trivia: [
      "天の川の中心方向にあるので、星がたくさん集まって見えるよ。",
      "ティーポットの注ぎ口から湯気のように天の川が立ち上って見える。",
    ],
    genres: ["animal", "myth", "zodiac"],
  },
  {
    id: "pegasus",
    name: "Pegasus",
    nameJa: "ペガスス座",
    stars: ["Markab", "Scheat", "Algenib", "Enif", "Alpheratz"],
    lines: [
      ["Scheat", "Markab"],
      ["Markab", "Algenib"],
      ["Algenib", "Alpheratz"],
      ["Alpheratz", "Scheat"],
      ["Markab", "Enif"],
    ],
    description: "秋の夜空に大きく四角く見える「秋の四辺形」が目印だよ！",
    myth: "ギリシャ神話に登場する翼の生えた馬、ペガサスの姿。英雄ペルセウスを乗せて空を飛んだんだ。",
    emoji: "🐎",
    season: "autumn",
    trivia: [
      "「秋の四辺形」はとても大きいので、最初は見つけにくいかも。でも一度覚えると良い目印になるよ。",
      "四辺形の一つの星（アルフェラッツ）は、実はアンドロメダ座の星なんだ。",
    ],
    genres: ["animal", "myth"],
  },
  {
    id: "andromeda",
    name: "Andromeda",
    nameJa: "アンドロメダ座",
    stars: ["Alpheratz", "Mirach"],
    lines: [["Alpheratz", "Mirach"]],
    description: "秋の四辺形から連なる星の列が目印。有名なアンドロメダ銀河(M31)がある星座だよ。",
    myth: "エチオピアの王女アンドロメダの姿。海の怪物のいけにえにされそうになったところを、英雄ペルセウスに助けられたんだ。",
    emoji: "⛓️",
    season: "autumn",
    trivia: [
      "アンドロメダ銀河は、肉眼でもぼんやりと見えることがあるよ。双眼鏡を使うと見つけやすい。",
      "ペガスス座の「秋の四辺形」から見つけるのが定番。",
    ],
    genres: ["hero", "myth"],
  },
  {
    id: "aries",
    name: "Aries",
    nameJa: "おひつじ座",
    stars: ["Hamal", "Sheratan"],
    lines: [["Hamal", "Sheratan"]],
    description: "春の夜空に見える黄道十二星座のひとつ。ハマルとシェラタンが目印だよ。",
    myth: "金色の毛を持つ魔法の羊。英雄たちを乗せて空を飛んだ後、ゼウスによって星座にされたんだ。",
    emoji: "🐏",
    season: "spring",
    trivia: ["黄道十二星座の始まりの星座として知られているよ。", "明るい星は少ないけど、見つけられると嬉しい星座。"],
    genres: ["animal", "myth", "zodiac"],
  },
  {
    id: "cancer",
    name: "Cancer",
    nameJa: "かに座",
    stars: ["Altarf"],
    lines: [],
    description: "春から夏にかけて見える黄道十二星座のひとつ。明るい星は少ないけど、プレセペ星団(M44)が有名だよ。",
    myth: "英雄ヘラクレスに踏みつぶされてしまった巨大な化け蟹。その勇敢さを女神ヘラに認められて星座になったんだ。",
    emoji: "🦀",
    season: "spring",
    trivia: ["プレセペ星団は双眼鏡で見るとたくさんの星が見えてきれいだよ。", "都会の明るい空では見つけにくい星座のひとつ。"],
    genres: ["animal", "myth", "zodiac"],
  },
  {
    id: "libra",
    name: "Libra",
    nameJa: "てんびん座",
    stars: ["Zubenelgenubi", "Zubeneschamali"],
    lines: [["Zubenelgenubi", "Zubeneschamali"]],
    description: "春の終わりから夏にかけて見える黄道十二星座のひとつ。さそり座の近くにあるよ。",
    myth: "正義の女神アストライアが持つ、善と悪をはかる天秤だとされているよ。昔はさそり座の一部だったんだ。",
    emoji: "⚖️",
    season: "summer",
    trivia: ["黄道十二星座の中で唯一、生き物ではない星座だよ。", "ズベンエルゲヌビとズベンエスカマリは「南の爪」「北の爪」という意味。"],
    genres: ["myth", "tool", "zodiac"],
  },
  {
    id: "capricornus",
    name: "Capricornus",
    nameJa: "やぎ座",
    stars: ["Deneb Algedi"],
    lines: [],
    description: "夏の終わりから秋にかけて見える黄道十二星座のひとつ。逆三角形の形が目印だよ。",
    myth: "上半身がヤギ、下半身が魚という不思議な姿の牧神パーンが変身した姿。驚いて水に飛び込んだ時にこうなったんだって。",
    emoji: "🐐",
    season: "autumn",
    trivia: ["誕生日占いで有名だけど、星座自体は暗めの星でできているよ。", "海王星が発見された星座としても知られているんだ。"],
    genres: ["animal", "myth", "zodiac"],
  },
  {
    id: "aquarius",
    name: "Aquarius",
    nameJa: "みずがめ座",
    stars: ["Sadalmelik", "Sadalsuud"],
    lines: [["Sadalmelik", "Sadalsuud"]],
    description: "秋の夜空に見える黄道十二星座のひとつ。水瓶をかつぐ人の姿をしているよ。",
    myth: "大神ゼウスに仕えた美少年ガニメデが、神々のために水瓶からお酒を注いでいる姿だとされているよ。",
    emoji: "🏺",
    season: "autumn",
    trivia: ["みずがめ座のあたりは、流れ星（流星群）がよく見られることで有名だよ。", "大きな星座だけど、明るい星が少ないので全体像はつかみにくいかも。"],
    genres: ["hero", "myth", "zodiac"],
  },
  {
    id: "pisces",
    name: "Pisces",
    nameJa: "うお座",
    stars: ["Alpherg"],
    lines: [],
    description: "秋から冬にかけて見える黄道十二星座のひとつ。2匹の魚がリボンで結ばれた姿をしているよ。",
    myth: "美の女神アフロディーテとその子エロスが、怪物から逃げるために魚に変身した姿だと言われているよ。",
    emoji: "♓",
    season: "autumn",
    trivia: ["黄道十二星座の最後の星座。", "春分点（太陽が天の赤道を南から北へ横切る点）がこの星座にあるんだ。"],
    genres: ["animal", "myth", "zodiac"],
  },
  {
    id: "hercules",
    name: "Hercules",
    nameJa: "ヘルクレス座",
    stars: ["Rasalgethi", "Kornephoros", "Pi Herculis", "Eta Herculis", "Zeta Herculis", "Epsilon Herculis"],
    lines: [
      ["Pi Herculis", "Eta Herculis"],
      ["Eta Herculis", "Zeta Herculis"],
      ["Zeta Herculis", "Epsilon Herculis"],
      ["Epsilon Herculis", "Pi Herculis"],
      ["Zeta Herculis", "Kornephoros"],
      ["Kornephoros", "Rasalgethi"],
    ],
    description: "夏の夜空に広がる大きな星座。ギリシャ神話最強の英雄ヘルクレスの姿だよ。",
    myth: "数々の冒険を乗り越えた英雄ヘルクレス。その功績をたたえ、大神ゼウスが星座にしたと言われているよ。",
    emoji: "💪",
    season: "summer",
    trivia: ["星座の形は「H」の形や、ひしゃげた台形（キーストーン）が目印。", "ヘルクレス座球状星団(M13)という有名な星団があるよ。"],
    genres: ["hero", "myth"],
  },
  {
    id: "perseus",
    name: "Perseus",
    nameJa: "ペルセウス座",
    stars: ["Mirfak", "Algol"],
    lines: [["Mirfak", "Algol"]],
    description: "秋から冬にかけて見やすい星座。アンドロメダ姫を助けた英雄ペルセウスの姿。",
    myth: "怪物メドゥーサを退治し、その首を持ってペガサスに乗り、いけにえにされそうだったアンドロメダ姫を助けた英雄だよ。",
    emoji: "🛡️",
    season: "autumn",
    trivia: ["ペルセウス座流星群は夏の終わりの風物詩として有名。", "アルゴルは「悪魔の星」とも呼ばれる変光星で、数日周期で明るさが変わるんだ。"],
    genres: ["hero", "myth"],
  },
  {
    id: "cepheus",
    name: "Cepheus",
    nameJa: "ケフェウス座",
    stars: ["Alderamin"],
    lines: [],
    description: "北の空に一年中見られる星座。カシオペヤ座の近くにあり、家のような五角形が目印。",
    myth: "古代エチオピアの王様で、カシオペヤ女王の夫、アンドロメダ姫のお父さんだよ。家族そろって星座になっているんだ。",
    emoji: "🤴",
    season: "all",
    trivia: ["約5500年後には、アルデラミンが北極星になると予測されているよ。", "カシオペヤ座とセットで見つけると覚えやすい。"],
    genres: ["hero", "myth", "northern"],
  },
  {
    id: "draco",
    name: "Draco",
    nameJa: "りゅう座",
    stars: ["Eltanin"],
    lines: [],
    description: "北の空で、おおぐま座とこぐま座を取り巻くように長く伸びる星座。",
    myth: "ギリシャ神話では、黄金のリンゴを守っていた竜。ヘルクレスに退治された後、空に上げられたと言われているよ。",
    emoji: "🐉",
    season: "all",
    trivia: ["とても大きな星座で、全天で8番目の広さを持つよ。", "りゅう座流星群の母天体としても知られる。"],
    genres: ["animal", "myth", "northern"],
},
{
    id: "corona-borealis",
    name: "Corona Borealis",
    nameJa: "かんむり座",
    stars: ["Alphecca"],
    lines: [],
    description: "春から夏にかけて、うしかい座の近くに見える半円形のきれいな星座。",
    myth: "クレタ島の王女アリアドネが結婚式で身につけた美しい冠が、星座になったと言われているよ。",
    emoji: "👑",
    season: "spring",
    trivia: ["7つの星が半円を描くように並んでいて、とても見つけやすい形をしているよ。", "アルフェッカは「欠けた皿」という意味も持つ。"],
    genres: ["myth", "tool"],
  },
  {
    id: "cetus",
    name: "Cetus",
    nameJa: "くじら座",
    stars: ["Deneb Kaitos", "Mira"],
    lines: [["Deneb Kaitos", "Mira"]],
    description: "秋の夜空に広がる大きな星座。海の怪物（化けクジラ）の姿をしているよ。",
    myth: "アンドロメダ姫を襲った海の怪物。ペルセウスによって石に変えられてしまったんだ。",
    emoji: "🐳",
    season: "autumn",
    trivia: ["ミラは「不思議な」という意味の有名な変光星で、約332日周期で明るさが大きく変わるよ。", "全天で4番目に大きな星座。"],
    genres: ["animal", "myth", "sea"],
  },
  {
    id: "crux",
    name: "Crux",
    nameJa: "みなみじゅうじ座",
    stars: ["Acrux", "Becrux", "Gacrux", "Imai"],
    lines: [
      ["Acrux", "Gacrux"],
      ["Becrux", "Imai"],
    ],
    description: "南半球の空で最も有名な星座！十字の形が目印で、南の方向を知るのに使われるよ。",
    myth: "比較的新しい星座のため古代の神話はないけれど、大航海時代に船乗りたちの重要な目印として使われたんだ。",
    emoji: "✨",
    season: "spring",
    trivia: [
      "日本では沖縄など南の地域でしか見ることができない、あこがれの星座。",
      "天の川の中にあり、近くにはコールサック（石炭袋）と呼ばれる暗黒星雲があるよ。",
    ],
    genres: ["southern", "tool"],
  },
  {
    id: "centaurus",
    name: "Centaurus",
    nameJa: "ケンタウルス座",
    stars: ["Rigil Kentaurus", "Hadar"],
    lines: [["Rigil Kentaurus", "Hadar"]],
    description:
      "南の空の大きな星座。太陽系に最も近い恒星「リギル・ケンタウルス（アルファ・ケンタウリ）」があることで有名だよ。",
    myth: "ギリシャ神話に登場する賢者ケイローン（または別のケンタウロス）の姿。多くの英雄を育てた先生なんだ。",
    emoji: "🧑‍🏫",
    season: "spring",
    trivia: [
      "リギル・ケンタウルスは、実は3つの星からなる連星系なんだ。",
      "日本ではほとんど見ることができない南天の星座。",
    ],
    genres: ["animal", "hero", "myth"],
  },
  {
    id: "eridanus",
    name: "Eridanus",
    nameJa: "エリダヌス座",
    stars: ["Achernar"],
    lines: [],
    description:
      "オリオン座の足元から始まり、南の空へとうねりながら続く、とても長い星座。「川」に見立てられているよ。",
    myth: "太陽の戦車を暴走させて地上を焼き尽くしそうになり、ゼウスの雷で撃ち落とされたファエトンが落ちた川、エーリダヌス川だとされているよ。",
    emoji: "🌊",
    season: "winter",
    trivia: [
      "全天で6番目に広い星座。",
      "終点にある星アケルナルは「川の果て」という意味で、とても明るい星だけど、日本では見ることができない。",
    ],
    genres: ["myth", "sea"],
  },
];